name: equipment
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.1.0
  flutter_launcher_icons: ^0.9.3
  freezed_annotation: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_form_builder: ^7.3.0
  mask_text_input_formatter: ^2.3.0
  form_builder_validators: ^8.1.1
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: any
  json_serializable: ^6.0.1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_general.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf
