name: equipment
description: A new Flutter project.


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  flutter_svg: ^1.0.3
  flutter_svg_provider: ^1.0.3
  flutter_launcher_icons: ^0.9.3
  freezed_annotation: ^2.0.3
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_storage: ^10.2.17
  flutter_form_builder: ^7.3.0
  mask_text_input_formatter: ^2.3.0
  form_builder_validators: ^8.1.1
  pin_code_fields: ^7.4.0
  flutter_bloc: ^8.0.1
  json_serializable: ^6.2.0
  json_annotation: ^4.5.0
  fluttertoast: ^8.0.9
  shared_preferences: ^2.0.15
  easy_autocomplete: ^1.5.0
  carousel_slider: ^4.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.1.11
  flutter_gen_runner: any
  freezed: ^2.0.3+1

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/ic_general.webp"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
        - asset: assets/fonts/Nunito-Medium.ttf
        - asset: assets/fonts/Nunito-SemiBold.ttf


flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true